### ISSUE TITLE
Is Raven DB's Voron engine suitable for our purposes?

### ISSUE THREAD

**Issue by ReubenBond** [OrleansContrib/Orleans.Consensus#4]
I havent looked into it.
https://github.com/ravendb/ravendb/tree/v3.0/Raven.Voron

The license might be permissive enough: https://github.com/ravendb/ravendb/blob/v3.0/license.txt

**Comment by richorama** [comment]
It looks interesting, but I wonder whether it's overkill. We just need the log, rather than a whole key-value store.

I'm not sure on the details but it looks like the Symas LMDB which it sits on is closed source and not free.
